AWSTemplateFormatVersion: '2010-09-09'
Resources:
  #VPCを作成
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: Name
        Value: VPC
  #Public Subnetを作成
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.10.0/24
      AvailabiltyZone: ap-northeast-1a
      Tags:
      - Key: Name
        Value: PublicSubnet
  #Private Subnetを作成
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.20.0/24
      AvailabiltyZone: ap-northeast-1a
      Tags:
      - Key: Name
        Value: PrivateSubnet
  #InternetGatewayを作成
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: CloudFormationInternetGateway
  #InternetGatewayをVPCにアタッチ
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
  #Public Subnet用のルートテーブルを作成
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: PublicRouteTable
  PublicRouting:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      GatewayId: !Ref InternetGateway
      DestinationCidrBlock: 0.0.0.0/0
  #ルートテーブルをサブネットにアタッチ
  PublicRouteTableAttachToPublicSubnetA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet
  #Public Subnet用セキュリティグループ
  SecurityGroupForPublicSubnet:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecurityGroupForPublicSubnet
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPC
  #Public SubnetにEC2を作成
  EC2onPublicSubnet:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ab3e16f9c414dee7
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref SecurityGroupForPublicSubnet
      Tags:
        - Key: Name
          Value: PublicEC2
  # ElacticIPを割り当て
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: !Ref VPC
      InstanceId: !Ref EC2onPublicSubnet
